model:
  name: efficient_ad
  model_size: small
  lr: 0.0001

data:
  source: mvtec
  path: Z:/Source_Python/EfficientAD/datasets/mvtec_anomaly_detection/bottle
  category: bottle
    
  # 공통 설정
  image_size: [256, 256]
  train_batch_size: 1
  eval_batch_size: 32

trainer:
  max_epochs: 200
