model:
  name: efficient_ad
  model_size: small
  lr: 0.0001

data:
  source: ky
  name: ky
  path: F:/Source/EfficientAD/datasets/KY
  category: ky
    
  # 공통 설정
  image_size: [256, 256]
  train_batch_size: 1
  eval_batch_size: 32

trainer:
  max_epochs: 200
